In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("credit_default_train.csv")

In [3]:
data.head()

limit     sex        education   status  age  ps-sep  ps-aug  ps-jul  \
0   50000    male  graduate school      NaN   25       2       0       0   
1  200000    male       university  married   54      -1      -1      -1   
2   30000  female      high school  married   -1       2       3       2   
3  140000  female       university   single   -1       0       0       0   
4   60000  female      high school  married   36       1       2       2   

   ps-jun  ps-may       ...        ba-jun  ba-may  ba-apr  pa-sep  pa-aug  \
0       0       0       ...         49535   30358   30302    2130    1905   
1      -1      -1       ...          6335    4616    7956   10120    7852   
2       2       2       ...         30496   29731   29047       0    1700   
3       0       0       ...         25224   26855   23783    2000    2000   
4       0       0       ...         48738   49601   52773    1788       0   

   pa-jul  pa-jun  pa-may  pa-apr  credit_default  
0    1811    1100    1100    1200              no  
1    6336    4622    7956    5499              no  
2    1100       3    1053    1303              no  
3     900    2000   10000    5000              no  
4    1894    1801    3997       0             yes  

[5 rows x 24 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 24 columns):
limit             10000 non-null int64
sex               9900 non-null object
education         9873 non-null object
status            8178 non-null object
age               10000 non-null int64
ps-sep            10000 non-null int64
ps-aug            10000 non-null int64
ps-jul            10000 non-null int64
ps-jun            10000 non-null int64
ps-may            10000 non-null int64
ps-apr            10000 non-null int64
ba-sep            10000 non-null int64
ba-aug            10000 non-null int64
ba-jul            10000 non-null int64
ba-jun            10000 non-null int64
ba-may            10000 non-null int64
ba-apr            10000 non-null int64
pa-sep            10000 non-null int64
pa-aug            10000 non-null int64
pa-jul            10000 non-null int64
pa-jun            10000 non-null int64
pa-may            10000 non-null int64
pa-apr            10000 non-null i

In [5]:
data.describe()

limit           age        ps-sep        ps-aug        ps-jul  \
count   10000.000000  10000.000000  10000.000000  10000.000000  10000.000000   
mean   167197.000000     32.020200     -0.004000     -0.127800     -0.175700   
std    128975.488596     13.843119      1.132834      1.200921      1.193554   
min     10000.000000     -1.000000     -2.000000     -2.000000     -2.000000   
25%     50000.000000     26.000000     -1.000000     -1.000000     -1.000000   
50%    140000.000000     33.000000      0.000000      0.000000      0.000000   
75%    240000.000000     40.000000      0.000000      0.000000      0.000000   
max    780000.000000     75.000000      8.000000      7.000000      8.000000   

             ps-jun        ps-may        ps-apr         ba-sep         ba-aug  \
count  10000.000000  10000.000000  10000.000000   10000.000000   10000.000000   
mean      -0.234300     -0.263700     -0.297400   51490.704100   49239.438400   
std        1.169333      1.147386      1.147295   73740.383345   70777.470286   
min       -2.000000     -2.000000     -2.000000  -14386.000000  -69777.000000   
25%       -1.000000     -1.000000     -1.000000    3545.250000    2899.250000   
50%        0.000000      0.000000      0.000000   22246.000000   21202.000000   
75%        0.000000      0.000000      0.000000   67681.000000   64412.750000   
max        8.000000      8.000000      8.000000  613860.000000  605943.000000   

             ba-jul         ba-jun         ba-may         ba-apr  \
count   10000.00000   10000.000000   10000.000000   10000.000000   
mean    46957.46680   43306.114300   40182.130200   38621.582700   
std     68948.62697   64519.910263   60732.330157   59325.339137   
min    -61506.00000  -24303.000000  -81334.000000 -209051.000000   
25%      2442.50000    2203.250000    1650.000000    1150.000000   
50%     19905.50000   19072.000000   18071.000000   16977.000000   
75%     60164.75000   54093.750000   49906.500000   48680.750000   
max    597415.00000  616836.000000  587067.000000  568638.000000   

              pa-sep        pa-aug         pa-jul         pa-jun  \
count   10000.000000  1.000000e+04   10000.000000   10000.000000   
mean     5651.344900  5.973676e+03    5131.898600    4719.769200   
std     15835.839092  2.251175e+04   15416.402957   14483.407778   
min         0.000000  0.000000e+00       0.000000       0.000000   
25%       997.000000  7.800000e+02     390.000000     261.500000   
50%      2081.500000  2.000000e+03    1800.000000    1500.000000   
75%      5019.000000  5.000000e+03    4500.000000    4000.000000   
max    493358.000000  1.227082e+06  417588.000000  292962.000000   

              pa-may         pa-apr  
count   10000.000000   10000.000000  
mean     4734.702900    5480.147400  
std     14912.375475   19361.411204  
min         0.000000       0.000000  
25%       200.000000     100.000000  
50%      1500.000000    1500.000000  
75%      4000.000000    4000.000000  
max    417990.000000  528666.000000

In [25]:
def getDistinctValues(df, column):
    print(column)
    values=df[column].unique()
    if(df[column].dtype == 'int64'):
        values.sort()
    print(values)

In [26]:
columns=data.columns
for c in columns:
    getDistinctValues(data, str(c))

limit
[ 10000  20000  30000  40000  50000  60000  70000  80000  90000 100000
 110000 120000 130000 140000 150000 160000 170000 180000 190000 200000
 210000 220000 230000 240000 250000 260000 270000 280000 290000 300000
 310000 320000 330000 340000 350000 360000 370000 380000 390000 400000
 410000 420000 430000 440000 450000 460000 470000 480000 490000 500000
 510000 520000 530000 540000 550000 560000 570000 580000 590000 600000
 610000 620000 630000 640000 650000 660000 680000 700000 710000 740000
 750000 780000]
sex
['male' 'female' nan]
education
['graduate school' 'university' 'high school' nan 'others']
status
[nan 'married' 'single' 'others']
age
[-1 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 75]
ps-sep
[-2 -1  0  1  2  3  4  5  6  7  8]
ps-aug
[-2 -1  0  1  2  3  4  5  6  7]
ps-jul
[-2 -1  0  1  2  3  4  5  6  7  8]
ps-jun
[-2 -1  0  2  3  4  5  6  7  8]
ps-may
[-

In [27]:
def correctype(column):
    for x in column:
        if(type(x) != column.dtype):
            print(type(x), ": " ,str(x))

In [28]:
for c in data.columns:
    values=data[str(c)].unique()
    print("NAME: ", c , " TYPE: ", values.dtype)
    correctype(values)

NAME:  limit  TYPE:  int64
NAME:  sex  TYPE:  object
<class 'str'> :  male
<class 'str'> :  female
<class 'float'> :  nan
NAME:  education  TYPE:  object
<class 'str'> :  graduate school
<class 'str'> :  university
<class 'str'> :  high school
<class 'float'> :  nan
<class 'str'> :  others
NAME:  status  TYPE:  object
<class 'float'> :  nan
<class 'str'> :  married
<class 'str'> :  single
<class 'str'> :  others
NAME:  age  TYPE:  int64
NAME:  ps-sep  TYPE:  int64
NAME:  ps-aug  TYPE:  int64
NAME:  ps-jul  TYPE:  int64
NAME:  ps-jun  TYPE:  int64
NAME:  ps-may  TYPE:  int64
NAME:  ps-apr  TYPE:  int64
NAME:  ba-sep  TYPE:  int64
NAME:  ba-aug  TYPE:  int64
NAME:  ba-jul  TYPE:  int64
NAME:  ba-jun  TYPE:  int64
NAME:  ba-may  TYPE:  int64
NAME:  ba-apr  TYPE:  int64
NAME:  pa-sep  TYPE:  int64
NAME:  pa-aug  TYPE:  int64
NAME:  pa-jul  TYPE:  int64
NAME:  pa-jun  TYPE:  int64
NAME:  pa-may  TYPE:  int64
NAME:  pa-apr  TYPE:  int64
NAME:  credit_default  TYPE:  object
<class 'str'> :  n